[project]
name = "celiacwriteoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tanner Hamilton", email = "155474958+TannerHamilton123@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "python-dotenv>=1.0.1",
    "receipt-ocr>=0.3.1",
    "sendgrid>=6.11.0",
]

[project.scripts]
celiacwriteoff = "celiacwriteoff:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
pythonpath = ["src/celiacwriteoff/backend"]
testpaths = ["tests"]
